export * from "./about-section";
export * from "./academy-section";
export * from "./bottom-section";
export * from "./case-studies-section";
export * from "./clients-section";
export * from "./hero-section";
export * from "./pricing-section";
export * from "./process-section";
export * from "./services-section";
